name: quran_kareem
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.4
  dio: ^5.8.0+1
  get_it: ^8.0.3
  pretty_dio_logger: ^1.4.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  dartz: ^0.10.1
  skeletonizer: ^1.4.3
  flutter_svg: ^2.0.17
  easy_localization: ^3.0.7+1
  shared_preferences: ^2.5.3
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
